[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "evomof"
version = "0.1.0"
description = "Evolutionary optimisation of Grassmannian frames"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.0.0",
    "scipy>=1.13.0",
    "cma>=3.2.0",
    "pymanopt>=0.4",
]
license = { text = "Apache-2.0" }

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.mypy]
python_version = "3.11"
strict = true

[[tool.mypy.overrides]]
module = "cma.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pymanopt"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pymanopt.*"
ignore_missing_imports = true

[tool.hatch.envs.default]
dependencies = [
    "pytest",
    "black",
    "ruff",
    "mypy",
]
post-install = "python -m pip install -e .[dev]"

[tool.hatch.envs.default.scripts]
lint = "ruff check src tests && black --check src tests"
test = "pytest -q"
typecheck = "mypy -p evomof"
bench = "python bench/quick_benchmark.py"

