import: models.projection_pramp:ProjectionPRampModel
init:
  sigma0: 0.3
  max_gen: 50000
  seed: 42
  scheduler:
    import: frameopt.model.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+9
      window: 100