import: models.projection_pramp:ProjectionPRampModel
init:
  sigma0: 0.3
  max_gen: 120000
  seed: 42
  scheduler:
    import: frameopt.models.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+15
      window: 100