import: models.riemannian_pramp:RiemannianPRampModel
init:
  sigma0: 0.3
  max_gen: 80000
  seed: 42
  scheduler:
    import: frameopt.optim.utils.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+12
      window: 100