import: models.cg_pramp:CGPRampModel
init:
  maxiter: 50000
  seed: 42
  step: 100
  scheduler:
    import: frameopt.optim.utils.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+15
      window: 5