import: models.cg_pramp:CGPRampModel
init:
  maxiter: 1500
  seed: 42
  step: 10
  scheduler:
    import: evomof.optim.utils.p_scheduler:AdaptivePScheduler
    init:
      p0: 4.0
      p_max: 1.0e+9
      window: 5